[package]
name = "sage"
version = "0.1.1"
authors = ["rvillegasm"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.9.22"
dirs = "2.0.2"
indicatif = "0.13.0"
yaml-rust = "0.4.3"