name: Rust CI

on: [push, pull_request]

jobs:
  fmt:
    name: Format Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo fmt --all -- --check
  
  clippy:
    name: Static Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo clippy -- -D warnings

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: cargo build --verbose
  
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: cargo test --verbose
